# permissions for end users to edit osphealthchecks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: osphealthcheck-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: osphealthcheck
    app.kubernetes.io/part-of: osphealthcheck
    app.kubernetes.io/managed-by: kustomize
  name: osphealthcheck-editor-role
rules:
- apiGroups:
  - monitoring.spark.co.nz
  resources:
  - osphealthchecks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.spark.co.nz
  resources:
  - osphealthchecks/status
  verbs:
  - get
